### PR TITLE
fix: :bug: prevent the cell click event when clicking the HeaderActionIcon and close #409 #452

### LINKED ISSUE #409: 🐛 选中行头后下钻icon显示错位
### 🏷 Version
0.1.14
### 🖋 Description
点击行头后hover至其他行头
image

### PR DESCRIPTION
**Pull request by xingwanying**
…nIcon

### 👀 PR includes

🐛 Bugfix

- [x] Solve the issue and close #409 #452 

### 📝 Description

- Reset the interaction after drill-down or clear the drill-down which is needed to hide the tooltip.
- Clear the interaction state after clicking the HeaderActionIcon.
- Prevent the cell click event when clicking the HeaderActionIcon.

### 🖼️ Screenshot

| Before | After |
| ------ | ----- |
| ❌      | ✅     |
| image| image|

### CODE REVIEW

**Review by qubaomingg — DISMISSED** [review]
LG

File: packages/s2-core/src/interaction/event-controller.ts [hunk 1]
```diff
@@ -322,12 +323,22 @@ export class EventController {
             this.spreadsheet.emit(S2Event.DATA_CELL_CLICK, event);
             break;
           case CellTypes.ROW_CELL:
+            // 屏蔽 actionIcons的点击，只有HeaderCells 需要， DataCell 有状态类 icon， 不需要屏蔽
+            if (this.target.cfg?.type === 'image') {
```
Comment (wjgogogo) [inline packages/s2-core/src/interaction/event-controller.ts:327]: `image`可以抽一个常量

Comment (lijinke666) [reply packages/s2-core/src/interaction/event-controller.ts:327]: 抽个公共方法 或者 getter

File: packages/s2-core/src/interaction/event-controller.ts [hunk 2]
```diff
@@ -322,12 +328,22 @@ export class EventController {
...
             break;
           case CellTypes.ROW_CELL:
+            // 屏蔽 actionIcons的点击，只有HeaderCells 需要， DataCell 有状态类 icon， 不需要屏蔽
+            if (this.getTargetType() === IMAGE) {
+              break;
+            }
             this.spreadsheet.emit(S2Event.ROW_CELL_CLICK, event);
             break;
           case CellTypes.COL_CELL:
+            if (this.getTargetType() === IMAGE) {
```
Comment (lijinke666) [inline packages/s2-core/src/interaction/event-controller.ts:338]: 为啥不直接抽个 isImageTargetType 的函数

Comment (xingwanying) [reply packages/s2-core/src/interaction/event-controller.ts:338]: 因为我不知道之后会不会还有其他的targetType
