### PR TITLE
fix: 修复维度字段中包含 [&] 分隔符导致的获取数据不正确的问题

### LINKED ISSUE #2487: 🐛排序 按汇总排序 结果错乱
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |     1.54.1    |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [ x ] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

1.54.1版本的按值排序出来的结果是乱的，当降到1.49.0时正常

### ⌨️ Code Snapshots

官网链接：
https://s2.antv.antgroup.com/zh/examples/analysis/sort/#custom-totals

代码链接：
https://pastebin.ubuntu.com/p/NHw3BFmcSw/

仅是s2DataConfig不同，其它相同。

### 🤔 Steps to Reproduce
将代码执行，可发现 sortParams[0] 下的 sortMethod 为 desc，即应为降序，但是对应的排在第一个的 count_1[&]origin 的值为1，5在1的后面。

### 😊 Expected Behavior
正确的结果：desc时5应该为第一个（1.49.0即这样），

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |     macOS 12.3    |
| Browser |     chrome: v120.0    |

### PR DESCRIPTION
**Pull request by wjgogogo**
### 👀 PR includes

✨ Feature

- [ ] New feature

🎨 Enhance

- [ ] Code style optimization
- [ ] Refactoring
- [ ] Change the UI
- [ ] Improve the performance
- [ ] Type optimization

🐛 Bugfix

- [x] Solve the issue and close #2487 

🔧 Chore

- [ ] Test case
- [ ] Docs / demos update
- [ ] CI / workflow
- [ ] Release version
- [ ] Other ()

### 🖼️ Screenshot

| Before | After |
| ------ | ----- |
| image    | image     |

### 🔍 Self-Check before the merge

- [ ] Add or update relevant docs.
- [ ] Add or update relevant demos.
- [ ] Add or update test case.
- [ ] Add or update relevant TypeScript definitions.

### CODE REVIEW

File: packages/s2-core/src/utils/dataset/pivot-data-set.ts [hunk 1]
```diff
@@ -214,11 +214,10 @@ export function getDataPath(params: DataPathParams) {
       const value = dimensionValues[i];
 
       if (isFirstCreate && currentMeta && !currentMeta?.has(value)) {
-        const id = dimensionValues
+        const currentDimensions = dimensionValues
           .slice(0, i + 1)
-          .map((it) => String(it))
-          .join(ID_SEPARATOR);
```
Comment (wjgogogo) [inline packages/s2-core/src/utils/dataset/pivot-data-set.ts:220]: 如果 field 数据本身包含了 `[&]`，比如 `count[&]origin`，这里 split 后的结果不一定是期望的结果

File: packages/s2-core/src/utils/dataset/pivot-data-set.ts [hunk 2]
```diff
@@ -536,7 +536,7 @@ export function flattenDimensionValues(params: {
     sortedDimensionValues,
   });
 
-  return metaValues.map((v) => v.id.split(ID_SEPARATOR));
```
Comment (wjgogogo) [inline packages/s2-core/src/utils/dataset/pivot-data-set.ts:539]: 如果 field 数据本身包含了 `[&]`，比如 `count[&]origin`，这里 split 后的结果不一定是期望的结果

**Review by lijinke666 — APPROVED** [review]
