### PR TITLE
fix: 修复明细表空数据占位符背景穿透的问题 close #3077

### LINKED ISSUE #3077: 🐛 TableSheet 在滚动时添加数据，然后在搜索过滤的时候，会出现视图异常
### 🏷  S2 Version / S2 版本

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |  2.1.8  |
| @antv/s2-react |  2.1.6  |
| @antv/s2-react-components   |  |

### 💻 Sheet Type / 表格类型

- [ ] PivotSheet
- [X] TableSheet
- [ ] PivotChartSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Describe the bug / 问题描述

TableSheet 在滚动时添加数据，然后在搜索过滤的时候，会出现视图异常。

### ⌨️ Code Snapshots / 代码片段

https://codesandbox.io/p/sandbox/silly-goldstine-c7j7ww

### 🔗 Reproduction link / 复现链接

https://codesandbox.io/p/sandbox/silly-goldstine-c7j7ww

### 📋 Steps to Reproduce the Bug or Issue / 重现步骤

1. 拖动表格滚动条，滚动到100行左右（此时会加载数据）
2. 立即点击search按钮，会出现视图异常情况如下图所示
image

### 😊 Expected Behavior / 期望行为

加载数据后在过滤不存在的内容时，展示的应该只有empty提示

### 😅 Current Behavior / 当前行为

_No response_

### 💻 OS / 操作系统

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] Others / 其他

### 🌏 Browser / 浏览器

- [ ] Chrome
- [X] Edge
- [ ] Firefox
- [ ] Safari (Limited support / 有限支持)
- [ ] IE (Nonsupport / 不支持)
- [ ] Others / 其他

### PR DESCRIPTION
**Pull request by lijinke666**
### 👀 PR includes

🐛 Bugfix

- [x] Solve the issue and close #3077 

### 🖼️ Screenshot

| Before | After |
| ------ | ----- |
| image | 
image |

### 🔍 Self-Check before the merge

- [ ] Add or update relevant docs.
- [ ] Add or update relevant demos.
- [ ] Add or update test case.
- [ ] Add or update relevant TypeScript definitions.

### CODE REVIEW

File: packages/s2-core/src/facet/table-facet.ts [hunk 1]
```diff
@@ -148,6 +149,7 @@ export class TableFacet extends FrozenFacet {
         stroke: horizontalBorderColor,
         strokeWidth: horizontalBorderWidth,
         strokeOpacity: horizontalBorderColorOpacity,
+        fill: background?.color,
```
Comment (wjgogogo) [inline packages/s2-core/src/facet/table-facet.ts:152]: opacity 需要加上吗？
