### PR TITLE
fix(export): export link problem

### LINKED ISSUE #875: 🐛复制格式化数据和导出格式化数据的时候出现的问题
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       | - ^1.2.0        |
| @antv/s2-react | - ^1.2.0        |

### 🖋 Description
1、复制格式化数据和导出格式化数据的时候，会将url重定向到%60javascript:void(0)%60

1639014265596_5E42A88F-6179-45d4-B4BE-E13529AD483E
2、导出的时候，是否将标题导出可以让客户进行选择。
3、导出的csv文件，编码问题解决一下，打开后，中文都是乱码显示
image

### PR DESCRIPTION
**Pull request by YardWill**
### 👀 PR includes

✨ Feature

- [ ] New feature

🎨 Enhance

- [ ] Code style optimization
- [ ] Refactoring
- [ ] Change the UI
- [ ] Improve the performance
- [ ] Type optimization

🐛 Bugfix

- [x] Solve the issue and close #875 

🔧 Chore

- [ ] Test case
- [ ] Docs / demos update
- [ ] CI / workflow
- [ ] Release version
- [ ] Other ()

### 📝 Description

去掉组件内的a标签

### 🖼️ Screenshot

| Before | After |
| ------ | ----- |
| ❌      | ✅     |

### 🔍 Self Check before Merge

- [ ] Add or update relevant Docs.
- [ ] Add or update relevant Demos.
- [ ] Add or update relevant TypeScript definitions.

### CODE REVIEW

File: packages/s2-react/src/components/export/index.tsx [hunk 1]
```diff
@@ -71,16 +71,16 @@ export const Export: React.FC<ExportProps> = ({
   const menu = (
     <Menu>
       <Menu.Item key="copyOriginal" onClick={() => exportData(false)}>
-        <a href="`javascript:void(0)`">{copyOriginalText}</a>
+        {copyOriginalText}
```
Comment (xingwanying) [inline packages/s2-react/src/components/export/index.tsx:74]: 直接去掉样式会不会有问题? hover 高亮啥的加下css?

**Comment by lijinke666** [comment]
按理说 转  Blob 的时候加了 中文编码 不应该有乱码了吧 
image

**Review by xingwanying — APPROVED** [review]
