### PR TITLE
fix: 修复合并单元格被grid边框覆盖的问题

### LINKED ISSUE #1560: 合并单元格后，拖动表格内部滚动条，合并的单元格边框重新出现
### 1. 在官网示例，正常进行合并单元格操作，但尝试**滚动表格**后，原来合并的单元格边框再次出现
image
image

### 3. 同时发现配置在 s2Options 中的 mergedCellsInfo 属性中时，也会出现同样的情况。

### PR DESCRIPTION
**Pull request by wjgogogo**
### 👀 PR includes

✨ Feature

- [ ] New feature

🎨 Enhance

- [ ] Code style optimization
- [ ] Refactoring
- [ ] Change the UI
- [ ] Improve the performance
- [ ] Type optimization

🐛 Bugfix

- [x] Solve the issue and close #1560 

🔧 Chore

- [ ] Test case
- [ ] Docs / demos update
- [ ] CI / workflow
- [ ] Release version
- [ ] Other ()

### 📝 Description
原因：gridGroup用于绘制边框，绘制完成后会`toFront`，导致它被放在最上面的，把合并单元格给盖住了。
现在将所有的合并单元格收敛到`mergedCellsGroup`中统一管理，并且在`drawGrid`后，将`mergedCellsGroup` toFront，保证其不会被覆盖

### 🖼️ Screenshot

| Before | After |
| ------ | ----- |
|       |      |

### 🔍 Self-Check before the merge

- [ ] Add or update relevant docs.
- [ ] Add or update relevant demos.
- [ ] Add or update test case.
- [ ] Add or update relevant TypeScript definitions.

### CODE REVIEW

File: packages/s2-core/src/utils/interaction/merge-cell.ts [hunk 1]
```diff
@@ -384,7 +386,7 @@ export const updateMergedCells = (sheet: SpreadSheet) => {
   // 可见区域的所有cells
   const allCells = filter(
     sheet.panelScrollGroup.getChildren(),
-    (child) => !(child instanceof MergedCell),
+    (child) => child instanceof DataCell,
   ) as unknown as S2CellType[];
```
Comment (stone-lyl) [inline packages/s2-core/src/utils/interaction/merge-cell.ts:390]: 这个 `allCells`  和 `allVisibleCells` 可以提成一个方法。

Comment (wjgogogo) [reply packages/s2-core/src/utils/interaction/merge-cell.ts]: `interaction`中已经存在一个功能相同的方法，我直接用它就行

**Review by xingwanying — APPROVED** [review]
LG
