### PR TITLE
fix: 修复自定义列头导出数据时, 角头文本展示错误 close #2844

### LINKED ISSUE #2844: 🐛 交叉表自定义列头导出数据格式错位
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |  2.0.0-next.25       |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

交叉表自定义列头：
image
调用asyncGetAllPlainData导出数据，格式不对，感觉会把最后面列头替换行头文本，下面是控制台打印结果：
image

### 🔗 Reproduce Link

https://stackblitz.com/edit/vitejs-vite-m4qgeu?file=src%2FTestExport.tsx

### 😊 Expected Behavior

正常格式导出

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |         |
| Browser |         |

### PR DESCRIPTION
**Pull request by lijinke666**
### 👀 PR includes

🐛 Bugfix

- [x] Solve the issue and close #2844 

### 🖼️ Screenshot

| Before | After |
| ------ | ----- |
| image | image |

### 🔍 Self-Check before the merge

- [ ] Add or update relevant docs.
- [ ] Add or update relevant demos.
- [ ] Add or update test case.
- [ ] Add or update relevant TypeScript definitions.

### CODE REVIEW

File: packages/s2-core/__tests__/unit/utils/export/__snapshots__/export-pivot-spec.ts.snap [hunk 1]
```diff
@@ -228,7 +228,7 @@ province	city	数值	数值	数值	数值
 
 exports[`PivotSheet Export Test should export correct data with formatter for custom column headers 1`] = `
 "	自定义节点 a-1	自定义节点 a-1	自定义节点 a-1	自定义节点 a-1	自定义节点 a-2
-	自定义节点 a-2	自定义节点 a-1-1	自定义节点 a-1-1	自定义节点 a-1-2	
+	自定义节点 a-1-1	自定义节点 a-1-1	自定义节点 a-1-1	自定义节点 a-1-2
```
Comment (lijinke666) [inline packages/s2-core/__tests__/unit/utils/export/__snapshots__/export-pivot-spec.ts.snap:231]: 之前的快照是错的
