### PR TITLE
fix(core): highlight the column header cell and row header when data cell clicked

### LINKED ISSUE #2203: 🐛selectedCellHighlight不生效
### 🏷 Version

@antv/s2 1.44.0

-->

### Sheet Type

 PivotSheet
 TableSheet

### 🖋 Description

interaction.selectedCellHighlight:true 不生效

### ⌨️ Code Snapshots

import { PivotSheet, S2Options } from '@antv/s2';

fetch(
  'https://gw.alipayobjects.com/os/bmw-prod/2a5dbbc8-d0a7-4d02-b7c9-34f6ca63cff6.json',
)
  .then((res) => res.json())
  .then((dataCfg) => {
    const container = document.getElementById('container');

    const s2Options: S2Options = {
      width: 600,
      height: 480,
      interaction: {
        // 悬停高亮
        hoverHighlight: true,
        selectedCellHighlight: true // 这一行
      },
      tooltip: {
        showTooltip: true,
      },
    };
    const s2 = new PivotSheet(container, dataCfg, s2Options);

    s2.render();
  });

### 🤔 Steps to Reproduce

行列联动高亮 官方实例上添加selectedCellHighlight: true 点击后未出现整行整列高亮

### 😊 Expected Behavior

所在单元格行列应高亮

### 😅 Current Behavior

没有执行高亮

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |         |
| Browser |         |

### PR DESCRIPTION
**Pull request by tyr1dev**
### 👀 PR includes

✨ Feature

- [ ] New feature

🎨 Enhance

- [ ] Code style optimization
- [ ] Refactoring
- [ ] Change the UI
- [ ] Improve the performance
- [ ] Type optimization

🐛 Bugfix

- [x] Solve the issue and close #2203 

🔧 Chore

- [ ] Test case
- [x] Docs / demos update
- [ ] CI / workflow
- [ ] Release version
- [ ] Other ()

### 📝 Description

`selectedHighlight.colHeader` and `selectedHighlight.rowHeader` are not work, make them work.

In pr #1878 https://github.com/antvis/S2/pull/1878/files#diff-79be9be2d1570bcd35443dd13e103b787c004e69902bb9471ede6f336667bbc7L69, author deleted some codes,  but the new code https://github.com/antvis/S2/pull/1878/files#diff-0ba92ad42f39c956b8c70eaca83db2e9b9a6c4453e1e1a661d0b9d139c49e564R168 and then [header-cell.ts](https://github.com/antvis/S2/pull/1878/files#diff-8e2cddc3425be598ee2081cc4c0c175c1da46d3a2f825f0cd6ad303588f93163R383) will never get header cells in `interaction?.getCells`, and the code not work.

I do not know why the test case is passed, and I do not know how to fix it, sorry! You may help me to fix the test case, I will learn from your code, plz!

### 🖼️ Screenshot

| Before | After |
| ------ | ----- |
| ❌      | ✅     |

### 🔗 Related issue link

ref #1878 #2025 #2037 

### 🔍 Self-Check before the merge

- [x] Add or update relevant docs.
- [ ] Add or update relevant demos.
- [ ] Add or update test case.
- [ ] Add or update relevant TypeScript definitions.

### CODE REVIEW

File: packages/s2-core/src/interaction/base-interaction/click/data-cell-click.ts [hunk 1]
```diff
@@ -67,6 +70,28 @@ export class DataCellClick extends BaseEvent implements BaseEventImplement {
       });
       this.spreadsheet.emit(S2Event.GLOBAL_SELECTED, [cell]);
       this.showTooltip(event, meta);
+
+      // 点击单元格，高亮对应的行头、列头
+      const { rowId, colId, spreadsheet } = meta;
```
Comment (lijinke666) [inline packages/s2-core/src/interaction/base-interaction/click/data-cell-click.ts:75]: 把 `updateRowColCells` 这个方法删掉吧

https://github.com/antvis/S2/blob/c15f8c83d4fc25fc26f6e138b7c7f874256279bc/packages/s2-core/src/utils/interaction/select-event.ts#L100-L116

另外麻烦完善下这个单测, 覆盖一下 `rowHeader` 和 `colHeader` 的两个场景

https://github.com/antvis/S2/blob/c15f8c83d4fc25fc26f6e138b7c7f874256279bc/packages/s2-core/__tests__/unit/interaction/base-interaction/click/data-cell-click-spec.ts#L168

**Comment by lijinke666** [comment]
🐂

**Review by lijinke666 — APPROVED** [review]

**Review by lijinke666 — APPROVED** [review]
