### PR TITLE
fix: 修复合并单元格滚动出可视范围后边框绘制错误 close #3048

### LINKED ISSUE #3048: 🐛合并单元格在滚动后出现异常（最新版本会复现）
### 🏷  S2 Version / S2 版本

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |  v2.1.4  |
| @antv/s2-react | v2.1.3    |
| @antv/s2-react-components   |  |

### 💻 Sheet Type / 表格类型

- [X] PivotSheet
- [X] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Describe the bug / 问题描述

设置合并单元格生效后，滚动表格，再滚动回合并单元格的位置，发现合并的样式出现异常且不可预计

可查看原 issue [https://github.com/antvis/S2/issues/3032](https://github.com/antvis/S2/issues/3032)

file

### ⌨️ Code Snapshots / 代码片段

```
const s2Options: S2Options = {
      width: 600,
      height: 280,
      mergedCellsInfo: [
        [
          {
            "rowIndex": 0,
            "colIndex": 1
          },
          {
            "rowIndex": 1,
            "colIndex": 1,
            showText: true,
          },
          {
            "rowIndex": 2,
            "colIndex": 1,
          },
          {
            "rowIndex": 3,
            "colIndex": 1
          },
        ]
      ],
    };
```

### 🔗 Reproduction link / 复现链接

https://s2.antv.antgroup.com/examples/basic/table/#table

### 📋 Steps to Reproduce the Bug or Issue / 重现步骤

拉取最新的代码v2.1.4依然是复现的，并且官网demo也是一样的bug，需要滚动可以复现

复现案例：
1. 官网地址：https://s2.antv.antgroup.com/examples/basic/table/#table，代码参考 issue 内容
2. 拉取最新代码本地运行，复现如图：

按照下述代码修改一下 100w 数据的demo，反复滚动可出现：

```
const s2Options: SheetComponentOptions = {
  height: 480,
  mergedCellsInfo: [
        [
          {
            "rowIndex": 0,
            "colIndex": 1
          },
          {
            "rowIndex": 1,
            "colIndex": 1,
            showText: true,
          },
          {
            "rowIndex": 2,
            "colIndex": 1,
          },
          {
            "rowIndex": 3,
            "colIndex": 1
          },
        ]
      ],
  interaction: {
    scrollSpeedRatio: {
      vertical: 1,
      horizontal: 1,
    },
  },
  transformCanvasConfig(renderer) {
    renderer.setConfig({
      enableCulling: true,
    });
  },
};

const s2DataConfig: S2DataConfig = {
  fields: {
    // rows: [],
    columns: ['type', 'subType', 'province', 'city', 'number'],
    // values: ['number'],
  },
  data: generateRawData(
    { province: 1, city: 10 },
    { type: 10, subType: 10 },
  ),
};

// sheetType 也改成 table
```

### 😊 Expected Behavior / 期望行为

滚动后合并单元格显示正常

### 😅 Current Behavior / 当前行为

_No response_

### 💻 OS / 操作系统

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] Others / 其他

### 🌏 Browser / 浏览器

- [ ] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Safari (Limited support / 有限支持)
- [ ] IE (Nonsupport / 不支持)
- [ ] Others / 其他

### PR DESCRIPTION
**Pull request by lijinke666**
### 👀 PR includes

🐛 Bugfix

- [ ] Solve the issue and close #3048 

### 📝 Description

背景见 #3048 

```ts
  mergedCellsInfo: [
    [
      {
        rowIndex: 0,
        colIndex: 1,
      },
      {
        rowIndex: 1,
        colIndex: 1,
        showText: true,
      },
    ],
  ]
```

### 🖼️ Screenshot

| Before | After |
| ------ | ----- |
| image | image |

### 🔍 Self-Check before the merge

- [ ] Add or update relevant docs.
- [ ] Add or update relevant demos.
- [ ] Add or update test case.
- [ ] Add or update relevant TypeScript definitions.

### CODE REVIEW

File: packages/s2-core/src/utils/interaction/merge-cell.ts [hunk 1]
```diff
@@ -38,10 +38,18 @@ export const getInvisibleInfo = (
...
     if (meta) {
-      const cell = sheet?.options?.dataCell?.(meta, meta.spreadsheet);
+      const cell = sheet?.options?.dataCell?.(meta, meta.spreadsheet)!;
+
+      if (cell) {
+        /**
+         * 避免移除可视范围后丢失 position 属性:  https://github.com/antvis/S2/issues/3048
+         * 绘制线依赖 position 属性 => packages/s2-core/src/utils/cell/merged-cell.ts#getRightAndBottomCells
+         */
+        cell.position = [cellInfo.rowIndex!, cellInfo.colIndex!];
```
Comment (wjgogogo) [inline packages/s2-core/src/utils/interaction/merge-cell.ts]: 要不要把主链路那里抽一个方法，两个用同一个，不然这一块应该没人会知道

**Review by wjgogogo — APPROVED** [review]
