### PR TITLE
fix: 修复明细表自定义列头时, 隐藏列头后出现空白区域 close #3044

### LINKED ISSUE #3044: 🐛明细表自定义列头分组时，隐藏列后列头显示错误
### 🏷  S2 Version / S2 版本

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |    |
| @antv/s2-react |    |
| @antv/s2-react-components   |  |

### 💻 Sheet Type / 表格类型

- [ ] PivotSheet
- [X] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Describe the bug / 问题描述

明细表自定义列头分组时，隐藏列后列头显示错误，会有空白出现
image

### ⌨️ Code Snapshots / 代码片段

https://codesandbox.io/p/sandbox/clever-orla-n7lqf4?workspaceId=ws_8oNxnxhUCJz2Dk1z7Gf7rk

### 🔗 Reproduction link / 复现链接

https://codesandbox.io/p/sandbox/clever-orla-n7lqf4?workspaceId=ws_8oNxnxhUCJz2Dk1z7Gf7rk

### 📋 Steps to Reproduce the Bug or Issue / 重现步骤

 隐藏分组的叶子节点的第一个节点

### 😊 Expected Behavior / 期望行为

不显示空白

### 😅 Current Behavior / 当前行为

会显示空白

### 💻 OS / 操作系统

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] Others / 其他

### 🌏 Browser / 浏览器

- [ ] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Safari (Limited support / 有限支持)
- [ ] IE (Nonsupport / 不支持)
- [ ] Others / 其他

### PR DESCRIPTION
**Pull request by lijinke666**
### 👀 PR includes

🐛 Bugfix

- [x] Solve the issue and close #3044 

### 🖼️ Screenshot

| Before | After |
| ------ | ----- |
| image | image |

### 🔍 Self-Check before the merge

- [ ] Add or update relevant docs.
- [ ] Add or update relevant demos.
- [ ] Add or update test case.
- [ ] Add or update relevant TypeScript definitions.

### CODE REVIEW

File: packages/s2-core/src/facet/base-facet.ts [hunk 1]
```diff
@@ -537,6 +537,38 @@ export abstract class BaseFacet {
...
+      const parentNode = node?.parent;
+
+      if (prevColParent !== parentNode && parentNode) {
+        leafNodes.push(parentNode);
+
+        const firstVisibleChildNode = parentNode.children?.find(
+          (childNode) => childNode.width,
+        );
+        // 父节点 x 坐标 = 第一个未隐藏的子节点的 x 坐标
+        const parentNodeX = firstVisibleChildNode?.x || 0;
```
Comment (lijinke666) [inline packages/s2-core/src/facet/base-facet.ts:560]: 没有任何改动, 移动到 base-facet, 给明细表复用, 多列头下隐藏透视表之前修复过, 现在保持两边逻辑统一

**Review by wjgogogo — APPROVED** [review]
