### PR TITLE
fix: 修复点击单元格中的 icon 时无法获取到单元格 meta 信息的问题 close #2985

### LINKED ISSUE #2985: 🤔点击单元格中的icon，获取不到本行的数据，怎么可以点击图标获取当前行的数据
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |    ^2.0.0-next.26     |
| @antv/s2-react |    ^2.0.0-next.25     |
| @antv/s2-vue   |         |
 

### Sheet Type

使用的react中的透视表 SheetComponent 组件

- [ ] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet
- [ √ ] SheetComponent

### 🖋 Description

我使用的是  @antv/s2-react 中的 SheetComponent 组件 ，给 表格 的 s2Options增加 配置 icon，使单元格的数据前增加一个icon图标，代码如下：
      **conditions: {
        icon: [
          // 配置数据单元格
          {
            field: 'number',
            position: 'left',
            mapping() {
              return {
                icon: 'CellUp',
                fill: '#2498D1',
              };
            },
          },
        ],
      },**
      
**出现的问题是：当我点击单元格的时候可以获取到数据，但是当我单击到图标上时就会显示 undefined ；**
image

使用 headerActionIcons 这个属性只能在角头、列头、行头显示
image

**想达到的效果是：点击图标能获取当前行的数据**

### PR DESCRIPTION
**Pull request by lijinke666**
### 👀 PR includes

🐛 Bugfix

- [x] Solve the issue and close #2985 

### 🖼️ Screenshot

| Before | After |
| ------ | ----- |
| ❌      | ✅     |

### 🔍 Self-Check before the merge

- [ ] Add or update relevant docs.
- [ ] Add or update relevant demos.
- [ ] Add or update test case.
- [ ] Add or update relevant TypeScript definitions.

### CODE REVIEW

File: packages/s2-core/src/utils/interaction/formatter.ts [hunk 1]
```diff
@@ -1,12 +1,18 @@
...
-export const getBaseCellData = (event: Event): TargetCellInfo => {
+export const getBaseCellData = (
+  event: Event,
+  s2?: SpreadSheet,
+): TargetCellInfo => {
   const targetElement = event?.target as unknown as DisplayObject;
   const currentCellMeta = getAppendInfo(targetElement)?.meta;
-  const target = targetElement?.parentNode as S2CellType;
+  // https://github.com/antvis/S2/issues/2985
+  const target =
```
Comment (lijinke666) [inline packages/s2-core/src/utils/interaction/formatter.ts:14]: 如果是点击的单元格里的 icon, parentNode 并不是 Cell, 应该向上冒泡去找

image
