### PR TITLE
fix: 修复头部cell错误使用meta中formatter的问题，close #1014

### LINKED ISSUE #1014: 🐛自定义ColCell后列名会被格式化
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       | -   1.3.0 ～      |
| @antv/s2-react | -         |

### 🖋 Description
设置自定义colcell后，列名的文本会按照meta中设置的formatter进行格式化。

### 🔗 Reproduce Link
https://riddle.alibaba-inc.com/riddles/c8bbcaab

### PR DESCRIPTION
**Pull request by wjgogogo**
### 👀 PR includes

✨ Feature

- [ ] New feature

🎨 Enhance

- [ ] Code style optimization
- [x] 移除 col header中冗余的 `formatter`属性
- [ ] Change the UI
- [ ] Improve the performance
- [ ] Type optimization

🐛 Bugfix

- [x]  修复头部cell错误使用meta中formatter的问题

🔧 Chore

- [ ] Test case
- [ ] Docs / demos update
- [ ] CI / workflow
- [ ] Release version
- [ ] Other ()

### 📝 Description

```js
  meta: [
    {
      field: 'number',
      name: '数量',
    },
    {
      field: 'province',
      name: '省份',
      formatter: () => 'province',
    },
    {
      field: 'city',
      name: '城市',
      formatter: () => 'city',
    },
    {
      field: 'type',
      name: '类别',
      formatter: () => 'type',
    },
    {
      field: 'sub_type',
      name: '子类别',
    },
  ],
```

| Before | After |
| ------ | ----- |
| image    | image   |

### 🔗 Related issue link

close #1014 
### 🔍 Self Check before Merge

- [ ] Add or update relevant Docs.
- [ ] Add or update relevant Demos.
- [ ] Add or update relevant TypeScript definitions.

### CODE REVIEW

File: packages/s2-core/src/facet/header/col.ts [hunk 1]
```diff
@@ -7,14 +7,11 @@ import {
   FRONT_GROUND_GROUP_COL_SCROLL_Z_INDEX,
 } from '@/common/constant';
 import { ColCell } from '@/cell';
-import { Formatter } from '@/common/interface';
```
Comment (wjgogogo) [inline packages/s2-core/src/facet/header/col.ts:10]: col header里面的 formatter是冗余信息，完全不需要，所以将其删除，如果需要获取formatter，应该是统一走`dataSet.getFieldFormatter`, 而不是col header自己又单独搞一个字段出来

**Review by lijinke666 — APPROVED** [review]
