### PR TITLE
fix: 🐛  solve the wrong position of the grandTotal cell in multi-value mode and close #372

### LINKED ISSUE #372: 🐛多个数值时，总计格子显示出错
### 🏷 Version
latest
### 🖋 Description
多个数值时，总计格子显示出错
image

### PR DESCRIPTION
**Pull request by xingwanying**
### 👀 PR includes

🐛 Bugfix

- [x] Bug fix issue #372 

🔧 Chore

- [x] Test case

### 📝 Description
-  Solve the wrong position of the grandTotal cell in multi-value mode.
- Fix the wrong dataConfig of the default table sheet test.

### 🖼️ Screenshot

|  Before  |  After  |
|----|----|
|  ❌  |  ✅  |
|image|image|

### CODE REVIEW

File: packages/s2-core/src/theme/index.ts [hunk 1]
```diff
@@ -195,7 +195,7 @@ export const getTheme = (
       },
       icon: {
         fill: basicColors[0],
-        size: 12,
+        size: 10,
```
Comment (lijinke666) [inline packages/s2-core/src/theme/index.ts:198]: 为啥改为10了

**Review by lijinke666 — APPROVED** [review]
