### PR TITLE
fix: 多行文本二次渲染后少一行

### LINKED ISSUE #3087: 🐛react在rerender后maxLines计算错误
### 🏷  S2 Version / S2 版本

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |   ^2.1.9 |
| @antv/s2-react |  ^2.1.7  |
| @antv/s2-react-components   |  none |

### 💻 Sheet Type / 表格类型

- [ ] PivotSheet
- [x] TableSheet
- [ ] PivotChartSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Describe the bug / 问题描述

点击让组件重新渲染，3行变成了2行

### ⌨️ Code Snapshots / 代码片段

```
import { SheetComponent } from '@antv/s2-react';
import { useUpdate } from 'ahooks';
import { Button } from 'antd';

const data = Array(100).fill({
  province: 'aaaa'.repeat(100),
  city: 'aa',
});

export default function A() {
  const update = useUpdate();

  return (
    <div>
      <Button
        onClick={(e) => {
          update();
        }}
      >
        update
      </Button>

      <br />
      <SheetComponent
        sheetType="table"
        options={{
          width: 600,
          height: 480,
          style: {
            colCell: {
              maxLines: 3,
              wordWrap: true,
              textOverflow: 'ellipsis',
            },
            dataCell: {
              maxLines: 3,
              wordWrap: true,
              textOverflow: 'ellipsis',
            },
          },
        }}
        dataCfg={{
          fields: {
            columns: ['province', 'city'],
          },
          meta: [
            {
              field: 'province',
              name: '省份',
            },
            {
              field: 'city',
              name: '城市',
            },
          ],
          data,
        }}
      />
    </div>
  );
}
```

### 🔗 Reproduction link / 复现链接

_No response_

### 📋 Steps to Reproduce the Bug or Issue / 重现步骤

点按钮

### 😊 Expected Behavior / 期望行为

不要变成2行

### 😅 Current Behavior / 当前行为

重新渲染样式变更了

### 💻 OS / 操作系统

- [x] macOS
- [ ] Windows
- [ ] Linux
- [ ] Others / 其他

### 🌏 Browser / 浏览器

- [x] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Safari (Limited support / 有限支持)
- [ ] IE (Nonsupport / 不支持)
- [ ] Others / 其他

### PR DESCRIPTION
**Pull request by Alexzjt**
### 👀 PR includes

✨ Feature

- [ ] New feature

🎨 Enhance

- [ ] Code style optimization
- [ ] Refactoring
- [ ] Change the UI
- [ ] Improve the performance
- [ ] Type optimization

🐛 Bugfix

- [x] Solve the issue and close #3087 

🔧 Chore

- [x] Test case
- [ ] Docs / demos update
- [ ] CI / workflow
- [ ] Release version
- [ ] Other ()

### 🖼️ Screenshot

| Before | After |
| ------ | ----- |
| iShot_2025-02-01_21 38 54 | iShot_2025-02-01_21 39 18  |

### 🔗 Related issue link

https://github.com/antvis/S2/issues/3087

### 🔍 Self-Check before the merge

- [ ] Add or update relevant docs.
- [ ] Add or update relevant demos.
- [x] Add or update test case.
- [ ] Add or update relevant TypeScript definitions.

### CODE REVIEW

File: packages/s2-core/src/cell/base-cell.ts [hunk 1]
```diff
@@ -856,7 +856,7 @@ export abstract class BaseCell<T extends SimpleBBox> extends Group {
 
     const maxLines = Math.max(
       1,
-      Math.floor((displayHeight - padding) / lineHeight),
+      Math.round((displayHeight - padding) / lineHeight),
```
Comment (Alexzjt) [inline packages/s2-core/src/cell/base-cell.ts:859]: 问题根因分析
1. 数值截断逻辑矛盾
计算逻辑：(displayHeight - padding) / lineHeight = (61 - 16) / 16 = 2.8125
2. 条件判断逻辑缺陷
isCustomHeight 触发条件：只有当 isCustomHeight = true 时才会执行计算，但代码中该参数默认值为 false，在二次渲染时外部传入 true，导致逻辑分歧。

File: packages/s2-core/__tests__/bugs/issue-3087-spec.ts [hunk 2]
```diff
@@ -0,0 +1,59 @@
+/**
+ * @description spec for issue #3087
```
Comment (lijinke666) [inline packages/s2-core/__tests__/bugs/issue-3087-spec.ts]: 移到 packages/s2-core/__tests__/spreadsheet/multi-line-text-spec.ts
