### PR TITLE
fix: 🐛  tweak the corner cell icon position and close #464

### LINKED ISSUE #464: 🐛  行头 icon 位置
### 🏷 Version
latest

### 🖋 Description

image

http://dasbi-327.gz00b.dev.alipay.net/self_analysis.htm?Lang=zh_CN&channelType=SELF_ANALYSIS&selfAnalysisId=D2021101500161222000002042384&dsType=odps#/selfAnalysis/detail

打开后通过行列排序将销售渠道挂载列头后，icon 显示异常。
（屏幕宽度约 1467）

### PR DESCRIPTION
**Pull request by wjgogogo**
### 👀 PR includes

🐛 Bugfix

- [x] fix corner node bbox calculation
- [x] fix icon position in row and cornor cell 

### 🖼️ Screenshot

| Before | After |
| ------ | ----- |
| |    |

### 🔗 Related issue link

close #464

### CODE REVIEW

File: packages/s2-core/src/facet/header/corner.ts [hunk 1]
```diff
@@ -96,39 +97,35 @@ export class CornerHeader extends BaseHeader<CornerHeaderConfig> {
...
-        // different type different height
-        sNode.height = isPivotMode
-          ? colsHierarchy?.sampleNodeForLastLevel?.height
-          : height;
-        sNode.isPivotMode = isPivotMode;
-        sNode.cornerType = 'row';
-        cornerNodes.push(sNode);
-      }
+    // spreadsheet must have at least one node in last level
+    if (seriesNumberWidth && colsHierarchy?.sampleNodeForLastLevel) {
```
Comment (xingwanying) [inline packages/s2-core/src/facet/header/corner.ts:103]: 这个isPivotMode是不是已经没用了，table表的corner也不走这里

File: packages/s2-core/src/facet/header/corner.ts [hunk 2]
```diff
@@ -142,68 +139,59 @@ export class CornerHeader extends BaseHeader<CornerHeaderConfig> {
...
-        cNode.width = colsHierarchy.sampleNodeForLastLevel.width;
-        cNode.height = nodeHeight;
+        cNode.y = colNode.y;
+        cNode.width = width - columOffsetX;
+        cNode.height = colNode.originalHeight || colNode.height;
         cNode.field = field;
         cNode.isPivotMode = isPivotMode;
-        cNode.cornerType = 'col';
+        cNode.cornerType = CornerNodeType.Col;
         cNode.spreadsheet = s2;
```
Comment (xingwanying) [inline packages/s2-core/src/facet/header/corner.ts:195]: 这部分有测过各种小计总计的case不？
