### PR TITLE
fix(scroll): 修复移动端快速滚动时控制台报错 close #2266

### LINKED ISSUE #2266: 🐛移动端表格边界滚动行为异常
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |1.42.0|

### Sheet Type

- [X] PivotSheet
- [X] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

移动端表格边界滚动行为异常

### ⌨️ Code Snapshots
```
const s2DataConfig = {
  fields: {
    columns: ["province", "city", "type", "price"]
  },
  data: [
    {
      province: "浙江",
      city: "杭州",
      type: "笔",
      price: "1"
    },
    {
      province: "浙江",
      city: "杭州",
      type: "纸张",
      price: "2"
    },
    {
      province: "浙江",
      city: "舟山",
      type: "笔",
      price: "17"
    },
    {
      province: "浙江",
      city: "舟山",
      type: "纸张",
      price: "0.5"
    },
    {
      province: "吉林",
      city: "丹东",
      type: "笔",
      price: "8"
    },
    {
      province: "吉林",
      city: "白山",
      type: "笔",
      price: "9"
    },
    {
      province: "吉林",
      city: "丹东",
      type: " 纸张",
      price: "3"
    },
    {
      province: "吉林",
      city: "白山",
      type: "纸张",
      price: "1"
    },
    {
      province: "吉林",
      city: "白山",
      type: "笔",
      price: "9"
    },
    {
      province: "吉林",
      city: "丹东",
      type: " 纸张",
      price: "3"
    },
    {
      province: "吉林",
      city: "白山",
      type: "纸张",
      price: "1"
    },
    {
      province: "吉林",
      city: "白山",
      type: "笔",
      price: "9"
    },
    {
      province: "吉林",
      city: "丹东",
      type: " 纸张",
      price: "3"
    },
    {
      province: "吉林",
      city: "白山",
      type: "纸张",
      price: "1"
    },
    {
      province: "吉林",
      city: "白山",
      type: "笔",
      price: "9"
    },
    {
      province: "吉林",
      city: "丹东",
      type: " 纸张",
      price: "3"
    },
    {
      province: "吉林",
      city: "白山",
      type: "纸张",
      price: "1"
    },
    {
      province: "吉林",
      city: "白山",
      type: "笔",
      price: "9"
    },
    {
      province: "吉林",
      city: "丹东",
      type: " 纸张",
      price: "3"
    },
    {
      province: "吉林",
      city: "白山",
      type: "纸张",
      price: "1"
    }
  ]
};

const s2options = {
  width: 600,
  height: 500,
  interaction: {
    overscrollBehavior: 'auto'
  }
};
```
报错信息
`[Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.`

### 🔗 Reproduce Link
https://codesandbox.io/s/cocky-david-662ndr?file=/src/index.js

### 🤔 Steps to Reproduce
设备：移动端设备
涉及功能：滚动边界行为
前提条件：
- options.interaction.overscrollBehavior配置为'auto'
- 表格内容较多，出现滚动条

复现步骤：
- 触摸屏幕，拖动表格内容滚动至边界
- 继续滚动，控制台不断出现报错```[Intervention] Ignored attempt to cancel a touchend event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.```
- 并且表格会出现轻微抖动，例如滚动条滚至底部，继续拖动屏幕往下滚动，正确效果应该是表格本身不懂，触发页面往下滚动，实际上是页面虽然是在往下滚动，但是这个过程中表格本身很容易发生抖动

### 😊 Expected Behavior
正确应该是表格滚动条到达边界之后继续滚动，只有外部容器会滚动，表格本身不应发生抖动

### 😅 Current Behavior
目前是表格滚动条到达边界之后继续滚动，外部容器会滚动，但是表格本身发生了抖动，并且出现控制台报错

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |windows11|
| Browser |Chrome 105.0.5195.102|

### PR DESCRIPTION
**Pull request by lijinke666**
### 👀 PR includes

🐛 Bugfix

- [x] Solve the issue and close #2266 

### 📝 Description

移动端滚动时通过 `preventDefault()` 阻止父容器滚动, 在快速滚动时, 会有报错

参考解决方案: https://developer.mozilla.org/zh-CN/docs/Web/API/Event/cancelable#%E7%A4%BA%E4%BE%8B

image

### 🖼️ Screenshot

| Before | After |
| ------ | ----- |
| ❌      | ✅     |

### 🔍 Self-Check before the merge

- [ ] Add or update relevant docs.
- [ ] Add or update relevant demos.
- [ ] Add or update test case.
- [ ] Add or update relevant TypeScript definitions.

### CODE REVIEW

File: packages/s2-core/src/facet/base-facet.ts [hunk 1]
```diff
@@ -201,6 +201,7 @@ export abstract class BaseFacet {
       const originEvent = ev.event;
       const { deltaX, deltaY, x, y } = ev;
       // The coordinates of mobile and pc are three times different
+      // TODO: 手指快速往上滚动时, deltaY 有时会为负数, 导致向下滚动时然后回弹, 看起来就像表格在抖动, 需要判断滚动方向, next 版本未复现
```
Comment (lijinke666) [inline packages/s2-core/src/facet/base-facet.ts:204]: @antv/g-gesture@1.0.1 有 bug

image
