### PR TITLE
fix: 修复自定义计算总计时, 复制的数据不正确 close #2928

### LINKED ISSUE #2928: 🐛交叉表只有列维度时，同时开启行总计和列总计，复制的数据中行总计的值与表格实际渲染的值不符
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |         |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

交叉表只有列维度时，同时开启行总计（均值）和列总计（求和），调用`asyncGetAllPlainData` 函数得到的复制数据里面行总计的值与表格实际渲染的值不符

### ⌨️ Code Snapshots
直接使用官网示例在线演示 [链接](https://s2.antv.antgroup.com/zh/examples/analysis/totals/#dimension-group-col)，替换成下面代码
```
// organize-imports-ignore
import React from 'react';
import { Aggregation, S2DataConfig } from '@antv/s2';
import { SheetComponent, SheetComponentOptions } from '@antv/s2-react';
import '@antv/s2-react/dist/style.min.css';

fetch(
  'https://gw.alipayobjects.com/os/bmw-prod/cd9814d0-6dfa-42a6-8455-5a6bd0ff93ca.json',
)
  .then((res) => res.json())
  .then((res) => {
    const s2Options: SheetComponentOptions = {
      width: 600,
      height: 480,
      interaction: {
        copy: { enable: true },
      },
      totals: {
        col: {
          showGrandTotals: true,
          showSubTotals: true,
          reverseGrandTotalsLayout: true,
          calcGrandTotals: {
            // 设置总计汇总计算方式为求和
            aggregation: Aggregation.SUM,
          },
        },
        row: {
          showGrandTotals: true,
          calcGrandTotals: {
            // 设置总计汇总计算方式为均值
            aggregation: Aggregation.AVG,
          },
        },
      },
    };

    const s2DataConfig: S2DataConfig = {
      fields: {
        rows: ['province', 'city'],
        // columns: ['type', 'sub_type'],
        values: ['number'],
      },
      meta: res.meta,
      data: res.data,
    };

    reactDOMClient.createRoot(document.getElementById('container')).render(
      <SheetComponent
        dataCfg={s2DataConfig}
        options={s2Options}
        header={{
          export: {
            open: true,
          },
        }}
        adaptive={false}
      />,
    );
  });

```

### 🤔 Steps to Reproduce
点击react 组件的任意一个复制按钮
image

### 😊 Expected Behavior
希望表格显示的行总计与复制的行总计值一致

### 😅 Current Behavior
可以看到表格显示的行总计与复制的行总计值不一致
image

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |   window 10      |
| Browser |  chrome: v128.0.6613.86       |

### PR DESCRIPTION
**Pull request by lijinke666**
### 👀 PR includes

🐛 Bugfix

- [x] Solve the issue and close #2928 

### 🖼️ Screenshot

| Before | After |
| ------ | ----- |
| image | image |

### 🔍 Self-Check before the merge

- [ ] Add or update relevant docs.
- [ ] Add or update relevant demos.
- [ ] Add or update test case.
- [ ] Add or update relevant TypeScript definitions.

### CODE REVIEW

File: packages/s2-core/src/utils/export/copy/pivot-data-cell-copy.ts [hunk 1]
```diff
@@ -213,18 +214,22 @@ export class PivotDataCellCopy extends BaseDataCellCopy {
...
-      },
+      query,
       rowNode,
-      isTotals:
-        rowNode.isTotals ||
-        rowNode.isTotalMeasure ||
-        colNode.isTotals ||
-        colNode.isTotalMeasure,
+      isTotals,
+      totalStatus: getHeaderTotalStatus(rowNode, colNode),
```
Comment (lijinke666) [inline packages/s2-core/src/utils/export/copy/pivot-data-cell-copy.ts:232]: 复制的时候, 没传入 totalStatus, 所以始终是按照 SUM 取计算, 如果用户自定义了其他的聚合方式, 表格展现的数据就会和复制的数据对不上

https://github.com/antvis/S2/blob/a13eb274a0653140f26ddd9aa26ead9badf83b51/packages/s2-core/src/data-set/pivot-data-set.ts#L410-L411

**Review by wjgogogo — APPROVED** [review]
