### PR TITLE
fix: 🐛 solve the wrong render state when updating the dataCfg and close #285

### LINKED ISSUE #285: 🐛 交叉表重新渲染展示异常
### 🖋 Description
切换两个dataCfg 会出现异常
image

### 🔗 Reproduce Link
https://riddle.alibaba-inc.com/riddles/25401be9

### PR DESCRIPTION
**Pull request by xingwanying**
### 👀 PR includes

🐛 Bugfix

- [x] Bug fix issue #285

🔧 Chore

- [x] Docs / demos update

### 📝 Description
- Close #285
- Update the CHANGELOG

### 🖼️ Screenshot

|  Before  |  After  |
|----|----|
|  ❌  |  ✅  |
|  image | image |
| image |image|

### CODE REVIEW

File: packages/s2-core/__tests__/unit/data-process/pivot-spec.tsx [hunk 1]
```diff
@@ -2,9 +2,9 @@
  * 交叉表核心数据流程（保证基本数据正确）
  * */
 import { flattenDeep, get, size, uniq } from 'lodash';
-import { assembleDataCfg, assembleOptions } from 'tests/util/sheet-entry';
-import { getContainer } from 'tests/util/helpers';
-import { data } from 'tests/data/mock-dataset.json';
+import { assembleDataCfg, assembleOptions } from '../..//util/sheet-entry';
```
Comment (lijinke666) [inline packages/s2-core/__tests__/unit/data-process/pivot-spec.tsx:5]: ..// ?

**Comment by lijinke666** [comment]
顺便本地跑一下 lint:fix-style, ci 挂了

File: packages/s2-core/__tests__/unit/data-process/pivot-spec.tsx (hunk 1 above)
Comment (xingwanying) [reply packages/s2-core/__tests__/unit/data-process/pivot-spec.tsx:5]: 谢谢谢谢

**Review by lijinke666 — APPROVED** [review]
