### PR TITLE
fix(core): can reset tooltip.renderTooltip in setOptions

### LINKED ISSUE #2205: 🐛无法通过调用setOptions重写renderTooltip方法
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |    1.45.1     |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description
在PivotSheet实例化后，调用setOptions设置tooltip，无法重写renderTooltip方法。
只能通过tooltip.data.content去实现自定义tooltip内容。

### ⌨️ Code Snapshots
image

### 🔗 Reproduce Link
https://codesandbox.io/s/falling-fast-3q46p2?file=/src/App.vue

### 🤔 Steps to Reproduce
打开Reproduce Link，点击交叉表中的单元格，会发现自定义tooltip不生效。

### 😊 Expected Behavior
通过setOptions可以重写renderTooltip方法

### 😅 Current Behavior
通过setOptions无法重写renderTooltip方法

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |    macOS     |
| Browser |    Chrome     |

### PR DESCRIPTION
**Pull request by tyr1dev**
### 👀 PR includes

✨ Feature

- [ ] New feature

🎨 Enhance

- [ ] Code style optimization
- [ ] Refactoring
- [ ] Change the UI
- [ ] Improve the performance
- [ ] Type optimization

🐛 Bugfix

- [x] Solve the issue and close #2205 

🔧 Chore

- [x] Test case
- [x] Docs / demos update
- [ ] CI / workflow
- [ ] Release version
- [x] Other (new button in react playground which can reset tooltip with `setOptions`)

### 📝 Description

`s2.tooltip` is init in the pivot sheet constructor, `s2.setOptions` and `s2.render` can not reset it, so call `s2.initTooltip` manually if tooltip changed in `s2.setOptions`.

### 🖼️ Screenshot

| Before | After |
| ------ | ----- |
| ❌      | ✅     |

### 🔍 Self-Check before the merge

- [x] Add or update relevant docs.
- [x] Add or update relevant demos.
- [x] Add or update test case.
- [ ] Add or update relevant TypeScript definitions.

### CODE REVIEW

**Comment by lijinke666** [comment]
@tyr1dev Test case failed

File: packages/s2-core/src/sheet-type/spread-sheet.ts [hunk 1]
```diff
@@ -381,6 +381,11 @@ export abstract class SpreadSheet extends EE {
     } else {
       this.options = customMerge(this.options, options);
     }
+
+    if (reset || options.tooltip?.renderTooltip) {
```
Comment (lijinke666) [inline packages/s2-core/src/sheet-type/spread-sheet.ts:385]: 这种情况, 是不是 init 之前把上一次的 tooltip 给 销毁掉要好一点?

```suggestion
  private initTooltip() {
    this.tooltip?.destroy?.()
    this.tooltip = this.renderTooltip();
    ...
  }
```

File: packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts [hunk 2]
```diff
@@ -455,6 +455,18 @@ describe('PivotSheet Tests', () => {
     expect(s2.options.showSeriesNumber).toBeTruthy();
   });
 
+  test('should init new tooltip', () => {
+    class CustomTooltip extends BaseTooltip {}
```
Comment (lijinke666) [inline packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts:459]: 覆盖一下 `destroy` 有被 call 到吧

```ts
   const destroySpy = jest
      .spyOn(s2.tooltip, 'destroy')
      .mockImplementationOnce(() => {});

 expect(destroySpy).toHaveBeenCalledTimes(1)
```

File: packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts [hunk 3]
```diff
@@ -963,7 +975,10 @@ describe('PivotSheet Tests', () => {
     s2.store.set('test', 111);
 
     // restore mock...
-    (s2.tooltip.show as jest.Mock).mockRestore();
+    const tooltipShow = jest
```
Comment (lijinke666) [inline packages/s2-core/__tests__/unit/sheet-type/pivot-sheet-spec.ts:978]:
```suggestion
    const tooltipShowSpy = jest
```

**Review by lijinke666 — APPROVED** [review]
