### PR TITLE
fix: 修复linkTextFill不生效的问题, close #1191

### LINKED ISSUE #1191: 🐛跳转链接 的 链接文本颜色配置 linkTextFill	 不生效
**描述：跳转链接 的 链接文本颜色配置 linkTextFill	 不生效**

image

**复现：https://codesandbox.io/s/crimson-microservice-d6e6j6?file=/index.ts**

**@antv/s2 版本：1.12.2**

### PR DESCRIPTION
**Pull request by wjgogogo**
### 👀 PR includes

✨ Feature

- [ ] New feature

🎨 Enhance

- [ ] Code style optimization
- [ ] Refactoring
- [ ] Change the UI
- [ ] Improve the performance
- [ ] Type optimization

🐛 Bugfix

- [x] Solve the issue and close #1191 

🔧 Chore

- [ ] Test case
- [ ] Docs / demos update
- [ ] CI / workflow
- [ ] Release version
- [ ] Other ()

### 📝 Description
之前的`linkTextFill`是按照pc和mobile端处理处理的，其中：
* pc 只添加下划线
* mobile 才应用 `linkTextFill`配置
对用户来说极具迷惑性，现在pc和mobile都统一应用`linkTextFill`，唯一区别仅有：pc端添加下划线
### 🖼️ Screenshot
主题配置：

```js
{ 
   theme: {
      rowCell: {
        text: {
          linkTextFill: 'red',
        },
        bolderText: {
          linkTextFill: 'red',
        },
      }
}
```
| Before | After |
| ------ | ----- |
|   image   | image   |

### 🔍 Self Check before Merge

- [ ] Add or update relevant Docs.
- [ ] Add or update relevant Demos.
- [ ] Add or update relevant TypeScript definitions.

### CODE REVIEW

File: packages/s2-core/src/cell/base-cell.ts [hunk 1]
```diff
@@ -199,41 +199,34 @@ export abstract class BaseCell<T extends SimpleBBox> extends Group {
...
-        appendInfo: {
-          isRowHeaderText: true, // 标记为行头(明细表行头其实就是Data Cell)文本，方便做链接跳转直接识别
-          cellData: this.meta,
+    if (!showLinkFieldShape) {
+      return;
+    }
+
+    const device = this.spreadsheet.options.style.device;
+    // 配置了链接跳转
+    if (!isMobile(device)) {
```
Comment (lijinke666) [inline packages/s2-core/src/cell/base-cell.ts:208]: 加点测试？

**Review by lijinke666 — APPROVED** [review]
