### PR TITLE
fix: 修复组件层事件回调无法获取单元格信息 closes #2615 #2610

### LINKED ISSUE #2615: 🐛@antv/s2-vue 的 2.0 版本中 SheetComponent 组件的 dataCellClick 事件的回调函数的参数中的 target 和 viewMeta 的值为 undefined
### 🏷 Version

| Package        | Version       |
| -------------- | ------------- |
| @antv/s2       | 2.0.0-next.15 |
| @antv/s2-react |               |
| @antv/s2-vue   | 2.0.0-next.11 |

### Sheet Type

- [ ] PivotSheet
- [x] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

在 @antv/s2-vue 的 2.0 版本中 SheetComponent 组件的 dataCellClick 事件的回调函数的参数中的 target 和 viewMeta 的值为 undefined，1.0 版本不存在这个问题

### ⌨️ Code Snapshots

```vue
<template>
  <SheetComponent
    sheetType="table"
    :dataCfg="dataCfg"
    :options="s2Options"
    @dataCellClick="handleDataCellClick"
  />
</template>

<script setup lang="ts">
import { ref, shallowRef } from 'vue'
import { SheetComponent } from '@antv/s2-vue'

import type { S2DataConfig, S2Options } from '@antv/s2'

const dataCfg = shallowRef<S2DataConfig>({
  fields: { columns: ['province', 'city'] },
  meta: [
    { field: 'province', name: '省份' },
    { field: 'city', name: '城市' }
  ],
  data: [
    { province: '浙江', city: '杭州' },
    { province: '吉林', city: '长春' }
  ]
})

const s2Options = ref<S2Options>({ width: 600, height: 480 })

const handleDataCellClick = (e) => {
  console.log('dataCellClick', e)
}
</script>
```

### 🔗 Reproduce Link

https://codesandbox.io/p/devbox/antv-s2-issue-demo-w74rk9?file=%2Fsrc%2FApp.vue%3A4%2C23

### 🤔 Steps to Reproduce

鼠标左键点击数值单元格

### 😊 Expected Behavior

image

image

target 和 viewMeta 根据文档返回值

### 😅 Current Behavior

image

target 和 viewMeta 的值为 undefined

### 💻 System information

| Environment | Info          |
| ----------- | ------------- |
| System      | macOS 12.5    |
| Browser     | chrome v122.0 |

### PR DESCRIPTION
**Pull request by lijinke666**
### 👀 PR includes

🐛 Bugfix

- [x] Solve the issue and close #0

### 🖼️ Screenshot

| Before | After |
| ------ | ----- |
| image | image |

### 🔗 Related issue link

closes #2615 #2610

### 🔍 Self-Check before the merge

- [ ] Add or update relevant docs.
- [ ] Add or update relevant demos.
- [ ] Add or update test case.
- [ ] Add or update relevant TypeScript definitions.

### CODE REVIEW

File: packages/s2-core/src/utils/interaction/formatter.ts [hunk 1]
```diff
@@ -5,9 +5,9 @@ import { getAppendInfo } from './common';
 
 /* formate the base Event data */
 export const getBaseCellData = (event: Event): TargetCellInfo => {
-  const targetElement = event as unknown as DisplayObject;
+  const targetElement = event?.target as unknown as DisplayObject;
```
Comment (lijinke666) [inline packages/s2-core/src/utils/interaction/formatter.ts:8]: 应该是 event.target, 之前迁移 G 5.0 的时候写错了
