### PR TITLE
fix: 多指标行头总计节点宽度计算错误

### LINKED ISSUE #2164: 🐛v1.44.0 下 交叉表总计行值超出显示...，拖动列宽 ...没有消失  并且没有渲染更宽宽度的单元格
### 🏷 Version 
@antv/s2 v1.44.0

PivotSheet

### 交叉表总计行...拖动列宽没有适配

官网实例地址
https://s2.antv.antgroup.com/zh/examples/analysis/totals/#multiple-values
配置修改

修改s2DataConfig拖动列宽bug100%复现

```
const s2DataConfig = {
      fields: {
        rows: ['province', 'city'],
        columns: ['type'],
        values: ['price', 'cost'],
        valueInCols: false
      },
      meta: [
        {
          field: 'province',
          name: '省份',
        },
        {
          field: 'city',
          name: '城市',
        },
        {
          field: 'type',
          name: '商品类别',
        },
        {
          field: 'price',
          name: '价格价格价格价格价格',
        },
        {
          field: 'cost',
          name: '成本成本成本成本成本成本',
        },
      ],
      data,
    };
```

### PR DESCRIPTION
**Pull request by lcx-seima**
### 👀 PR includes

🐛 Bugfix

- [x] Solve the issue and close #2164 

### 📝 Description
多个数值放行头时，总计节点没有调整节点宽度。

### 🖼️ Screenshot

| Before | After |
| ------ | ----- |
|   CleanShot 2023-04-17 at 12 15 47@2x     |  CleanShot 2023-04-17 at 12 15 23@2x    |

### 🔍 Self-Check before the merge

- [ ] Add or update relevant docs.
- [ ] Add or update relevant demos.
- [ ] Add or update test case.
- [ ] Add or update relevant TypeScript definitions.

### CODE REVIEW

File: packages/s2-core/src/facet/pivot-facet.ts [hunk 1]
```diff
@@ -535,9 +535,11 @@ export class PivotFacet extends BaseFacet {
     if (isRowHeader) {
       // 填充行总单元格宽度
       grandTotalNode.width = hierarchy.width;
-      // 调整其叶子结点位置
+      // 调整其叶子结点位置和宽度
```
Comment (lijinke666) [inline packages/s2-core/src/facet/pivot-facet.ts:538]:
```suggestion
      // 调整其叶子节点位置和宽度
```

**Review by lijinke666 — APPROVED** [review]
