### PR TITLE
fix(export): export corner bug

### LINKED ISSUE #854: 🐛导出组件功能，导出文件表头缺失
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       | -     1.1.2    |
| @antv/s2-react | -    1.1.1     |

### 🖋 Description
1.导出组件，表头导出异常

### ⌨️ Code Snapshots
image
导出效果：
image

### 🔗 Reproduce Link
https://s2.antv.vision/zh/examples/react-component/export#export
### 🤔 Steps to Reproduce
问题：导出组件，表头缺失
1.选择下载原始数据
2.查看下载文件

### 😊 Expected Behavior
导出的文件表头正常显示
### 😅 Current Behavior
表头缺失，如图上图所示
### 💻 System information
Chrome 
版本 96.0.4664.55（正式版本） (x86_64)
macOS 11.6

### PR DESCRIPTION
**Pull request by YardWill**
### 👀 PR includes

✨ Feature

- [ ] New feature

🎨 Enhance

- [ ] Code style optimization
- [ ] Refactoring
- [ ] Change the UI
- [ ] Improve the performance
- [ ] Type optimization

🐛 Bugfix

- [x] Solve the issue and close #854 

🔧 Chore

- [ ] Test case
- [ ] Docs / demos update
- [ ] CI / workflow
- [ ] Release version
- [ ] Other ()

### 🖼️ Screenshot

| Before | After |
| ------ | ----- |
| ❌      | ✅     |

### 🔍 Self Check before Merge

- [ ] Add or update relevant Docs.
- [ ] Add or update relevant Demos.
- [ ] Add or update relevant TypeScript definitions.

### CODE REVIEW

File: packages/s2-core/src/utils/export/index.ts [hunk 1]
```diff
@@ -209,6 +199,29 @@ export const copyData = (
 
     // Generate the table header.
     headers = colHeader.map((item, index) => {
+      if (sheetInstance.isPivotMode()) {
+        const { columns, rows, data } = sheetInstance.facet.cornerHeader.cfg;
+        const colNode = data.filter((e) => e.cornerType === 'col');
+        const rowNode = data.filter((e) => e.cornerType === 'row');
```
Comment (lijinke666) [inline packages/s2-core/src/utils/export/index.ts:205]: import { CornerNodeType } from '@/common/interface/node';

> CornerNodeType 这个大小写不统一, 麻烦顺便改成首字母大写吧

image


"row" => CornerNodeType.Row

File: packages/s2-core/src/utils/export/index.ts [hunk 2]
```diff
@@ -209,6 +199,29 @@ export const copyData = (
...
+
+        if (index < colHeader.length - 1) {
+          return [
+            ...Array(rowLength - 1).fill(''),
+            colNode.find((v) => v.field === columns[index])?.label || '',
```
Comment (lijinke666) [inline packages/s2-core/src/utils/export/index.ts:210]: v => 同上

**Review by lijinke666 — APPROVED** [review]
