### PR TITLE
fix: 滚动动画，冻结行列滚动位置

### LINKED ISSUE #3117: 🐛 [BUG1]scrollTo 的动画不生效；[BUG2]frozen colCount 时，scrollToNode(colNode) 会将 Node 滚动到固定列的下方
### 🏷  S2 Version / S2 版本

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |   2.2.3 |

### 💻 Sheet Type / 表格类型

- [x] PivotSheet
- [ ] TableSheet
- [ ] PivotChartSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Describe the bug / 问题描述

1. BUG1: scrollTo 动画问题，官方示例中也不生效：[点击"滚动至成都市"](https://s2.antv.antgroup.com/examples/interaction/advanced#scroll-to-cell) 即可复现
2. BUG2: frozen 列时，interaction.scrollToNode(targetColNode) 将 Node 滚动到固定列下方，官方示例中可复现

### ⌨️ Code Snapshots / 代码片段

bug1: https://s2.antv.antgroup.com/examples/interaction/advanced#scroll-to-cell
动画不生效
```javascript
 s2.interaction.scrollTo({
        offsetY: {
          value: rowNode.y,
          animate: true,
        },
      });
```

bug2: 列头滚动到固定列的下方（我理解 scrollDataCell 应该也会存在此问题）
```javascript
const s2Options: S2Options = {
  // ...
  frozen: {
    colCount: 1,
  }
}

function scrollToCol(targetColNode) {
    s2Ins!.interaction.scrollToNode(targetColNode)
}
```

### 🔗 Reproduction link / 复现链接

_No response_

### 📋 Steps to Reproduce the Bug or Issue / 重现步骤

https://s2.antv.antgroup.com/examples/interaction/advanced#scroll-to-cell

### 😊 Expected Behavior / 期望行为

1. 动画生效
2. 有固定列时，能将元素 scrollNode 到视野内

### 😅 Current Behavior / 当前行为

_No response_

### 💻 OS / 操作系统

- [x] macOS
- [ ] Windows
- [ ] Linux
- [ ] Others / 其他

### 🌏 Browser / 浏览器

- [x] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Safari (Limited support / 有限支持)
- [ ] IE (Nonsupport / 不支持)
- [ ] Others / 其他

### PR DESCRIPTION
**Pull request by Alexzjt**
### 👀 PR includes

✨ Feature

- [ ] New feature

🎨 Enhance

- [ ] Code style optimization
- [ ] Refactoring
- [ ] Change the UI
- [ ] Improve the performance
- [ ] Type optimization

🐛 Bugfix

- [x] Solve the issue and close #3117 

🔧 Chore

- [x] Test case
- [ ] Docs / demos update
- [ ] CI / workflow
- [ ] Release version
- [ ] Other ()

### 🖼️ Screenshot

| Before | After |
| ------ | ----- |
|  iShot_2025-03-12_21 53 44     |  iShot_2025-03-12_21 55 36    |
|  iShot_2025-03-12_23 09 49  |  iShot_2025-03-12_23 10 07  |

### 🔍 Self-Check before the merge

- [ ] Add or update relevant docs.
- [ ] Add or update relevant demos.
- [x] Add or update test case.
- [ ] Add or update relevant TypeScript definitions.

### CODE REVIEW

**Review by lijinke666 — APPROVED** [review]

File: packages/s2-core/src/interaction/root.ts [hunk 1]
```diff
@@ -475,7 +477,7 @@ export class RootInteraction {
    * 滚动至顶部
    * @example s2.interaction.scrollToTop({ animate: true, skipScrollEvent: true })
    */
-  public scrollToTop(options?: CellScrollToOptions) {
+  public scrollToTop(options: CellScrollToOptions = { animate: true }) {
```
Comment (lijinke666) [inline packages/s2-core/src/interaction/root.ts]: 保持不变，文档如果有错误描述修正下吧

File: packages/s2-core/src/interaction/root.ts [hunk 2]
```diff
@@ -33,6 +34,7 @@ import type {
   ScrollOffsetConfig,
   ViewMeta,
 } from '../common/interface';
+import { FrozenFacet } from '../facet';
```
Comment (lijinke666) [inline packages/s2-core/src/interaction/root.ts]:
```suggestion
import type { FrozenFacet } from '../facet';
```

**Review by lijinke666 — APPROVED** [review]
