### PR TITLE
fix: multi measure render wrong and optimize sortedDimensionValues

### LINKED ISSUE #725: 🐛 多指标不展示
### 🏷 Version
v1.0.0-beta.9
### 🖋 Description

多个指标时指标只显示单个

### 🔗 Reproduce Link
https://riddle.alibaba-inc.com/riddles/43f3846a

### PR DESCRIPTION
**Pull request by yangzhanmei**
### 👀 PR includes

🎨 Enhance

- [ ] Code style optimization
- [x] Refactoring
- [ ] Change the UI
- [ ] Improve the performance
- [ ] Type optimization

🐛 Bugfix

- [x] Solve the issue and close #725 

🔧 Chore

- [x] Test case
- [ ] Docs / demos update
- [ ] CI / workflow
- [ ] Release version
- [ ] Other ()

### 📝 Description
fix: multi measure render wrong and optimize sortedDimensionValues
### 🖼️ Screenshot

| Before                         | After                         |
| ------------------------------ | ------------------------------ |
| ❌                             | ✅                              |

### 🔗 Related issue link

close #725 

### 🔍 Self Check before Merge

- [ ] Add or update relevant Docs.
- [ ] Add or update relevant Demos.
- [ ] Add or update relevant TypeScript definitions.

### CODE REVIEW

File: packages/s2-core/__tests__/bugs/issue-725-spec.tsx [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+import ReactDOM from 'react-dom';
+import * as mockDataConfig from 'tests/data/data-issue-725.json';
+import { getContainer } from '../util/helpers';
+import { S2Options } from '@/common/interface';
+import { SheetComponent } from '@/components/sheets';
+
+function MainLayout({ hierarchyType }: { hierarchyType: 'grid' | 'tree' }) {
+  const [s2Options] = React.useState<S2Options>();
+  return (
+    <SheetComponent
```
Comment (xingwanying) [inline packages/s2-core/__tests__/bugs/issue-725-spec.tsx:18]: 这个不用comment了吧，直接用原生，不是组件层面的bug，不方便拆包

File: packages/s2-core/__tests__/data/data-issue-725.json [hunk 2]
```diff
@@ -0,0 +1,248 @@
...
+  "fields": {
+    "columns": [],
+    "rows": ["area", "province", "city", "type", "sub_type"],
+    "values": ["price", "cost"]
+  },
+  "meta": [
+    {
+      "field": "price",
+      "name": "价格"
+    },
```
Comment (xingwanying) [inline packages/s2-core/__tests__/data/data-issue-725.json:11]: test data 不用这么多，能复现的最小集就行了吧

File: packages/s2-core/__tests__/bugs/issue-725-spec.tsx [hunk 3]
```diff
@@ -0,0 +1,40 @@
...
+    'should correct render %o with empty options',
+    (type) => {
+      function render() {
+        ReactDOM.render(
+          <MainLayout hierarchyType={type as 'grid' | 'tree'} />,
+          getContainer(),
+        );
+      }
+
+      expect(render).not.toThrowError();
```
Comment (xingwanying) [inline packages/s2-core/__tests__/bugs/issue-725-spec.tsx:37]: 这个expect是不是应该看看dataSet或者是layoutResult是否有正确结果，感觉这个没覆盖到0，0

**Review by xingwanying — APPROVED** [review]
LG
