### PR TITLE
fix(components): fix cannot update table size by container resized

### LINKED ISSUE #792: 🐛组件设置自适应时 容器大小改变时（非窗口resize）未自适应
### 🏷 Version
1.0.2
### 🖋 Description
设置adaptive = true

通过非窗口resize行为 改变容器窗口大小时，未触发自适应

### PR DESCRIPTION
**Pull request by lijinke666**
### 👀 PR includes

✨ Feature

- [ ] New feature

🎨 Enhance

- [ ] Code style optimization
- [x] Refactoring
- [ ] Change the UI
- [ ] Improve the performance
- [ ] Type optimization

🐛 Bugfix

- [x] Solve the issue and close #792 

🔧 Chore

- [ ] Test case
- [ ] Docs / demos update
- [ ] CI / workflow
- [ ] Release version
- [ ] Other ()

### 📝 Description

1. 重构 useResizeEffect, 支持容器级别的 resize
2. 将目前所有的 hooks 抽离到独立的文件, 便于维护
3. 修复一个很有意思的bug, canvas 没有设置为块级元素, canvas 始终和 父容器有5px的高度差, 导致每次 resize, 高度都是累加的 += 5px

image

image

### 🖼️ Screenshot

| Before                         | After                         |
| ------------------------------ | ------------------------------ |
| Kapture 2021-11-23 at 15 47 37 | Kapture 2021-11-23 at 15 46 08 |
| Kapture 2021-11-23 at 15 50 28 | Kapture 2021-11-23 at 15 51 47 |

### 🔗 Related issue link

close #792 

### 🔍 Self Check before Merge

- [x] Add or update relevant Docs.
- [x] Add or update relevant Demos.
- [x] Add or update relevant TypeScript definitions.

### CODE REVIEW

File: packages/s2-react/src/hooks/useResizeEffect.ts [hunk 1]
```diff
@@ -0,0 +1,69 @@
...
+    });
+
+    resizeObserver.observe(container, {
+      box: 'border-box',
+    });
+
+    return () => {
+      resizeObserver.unobserve(container);
+    };
+  }, [container, s2, adaptive, render, debounceRender]);
```
Comment (xingwanying) [inline packages/s2-react/src/hooks/useResizeEffect.ts:68]: 这里加 s2 是否会引起不必要的多次渲染？

Comment (lijinke666) [reply packages/s2-react/src/hooks/useResizeEffect.ts:68]: 不会的 resizeObserver.observe 监听后 是只有 容器宽高改变才会重新渲染, 及时 s2 变了也没关系, 不过这里用不到 s2, 我去掉吧

**Review by xingwanying — APPROVED** [review]
LG
