### PR TITLE
fix: 修复移动端禁用外部容器滚动不生效

### LINKED ISSUE #2902: 🐛移动端 图表滚动问题
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |         |
| @antv/s2-react |         |
| @antv/s2-vue   |         |

### Sheet Type

- [ ] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

恭喜你 你又创造了一个新BUG
next.28 移动端 图表的虚拟滚动不好用

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |         |
| Browser |         |

### PR DESCRIPTION
**Pull request by lijinke666**
### 👀 PR includes

✨ Feature

- [ ] New feature

🎨 Enhance

- [ ] Code style optimization
- [ ] Refactoring
- [ ] Change the UI
- [ ] Improve the performance
- [ ] Type optimization

🐛 Bugfix

- [x] Solve the issue and close #2902

🔧 Chore

- [ ] Test case
- [ ] Docs / demos update
- [ ] CI / workflow
- [ ] Release version
- [ ] Other ()

### 🖼️ Screenshot

| Before | After |
| ------ | ----- |
| ❌      | ✅     |

### 🔍 Self-Check before the merge

- [ ] Add or update relevant docs.
- [ ] Add or update relevant demos.
- [ ] Add or update test case.
- [ ] Add or update relevant TypeScript definitions.

### CODE REVIEW

File: packages/s2-core/src/facet/base-facet.ts [hunk 1]
```diff
@@ -1445,8 +1445,9 @@ export abstract class BaseFacet {
       event?.preventDefault?.();
     }
 
-    // 移动端的 prevent 存在于 originalEvent 上
-    const mobileEvent = (event as unknown as GraphEvent)?.originalEvent;
+    // 使用 G 对应的原生 TouchEvent，以达到移动端禁用外部容器滚动的效果
+    const mobileEvent =
+      (event as unknown as FederatedPointerEvent)?.nativeEvent || event;
```
Comment (lijinke666) [inline packages/s2-core/src/facet/base-facet.ts:1450]: G 5.0 的 nativeEvent 才对应原生 Event 事件，所以之前的 preventDefault 一直没生效
