### PR TITLE
fix: 修复浏览器窗口多次放大后表格渲染模糊 close #2884

### LINKED ISSUE #2884: 🐛浏览器缩放导致表格模糊问题
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |    next     |
| @antv/s2-react |    -     |
| @antv/s2-vue   |    -    |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

随意打开任意一个官网示例，连续两次放大浏览器显示比例，按（cmd + ）两次，第一次放大，表格显示清晰，第二次放大，表格显示模糊。

### ⌨️ Code Snapshots

使用官网示例：https://s2.antv.antgroup.com/zh/examples/case/data-preview#house

### 🤔 Steps to Reproduce

按住cmd + ，放大浏览器比例，第一次放大，可以清晰展现表格，接着放大第二次，表格展现模糊，100%复现。
如果把hd设置为false，则可避免此问题
### 😊 Expected Behavior

1、保持清晰显示
2、在文档中正确描述“hd：true / false” 配置的区别，现在感觉hd: false 才可保证高清适配
### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |    macOS Sonoma 14.5     |
| Browser |    edge 127.0.2651.86     |

### PR DESCRIPTION
**Pull request by lijinke666**
### 👀 PR includes

🐛 Bugfix

- [x] Solve the issue and close #2884

### 📝 Description

系分 VisualViewport resize 场景下 Mac 触控板和浏览器窗口的区分, 避免相互冲突设置错误的 DPR

### 🖼️ Screenshot

| Before | After |
| ------ | ----- |
| Kapture 2024-09-12 at 15 21 27 | Kapture 2024-09-12 at 15 19 03 |

### 🔍 Self-Check before the merge

- [ ] Add or update relevant docs.
- [ ] Add or update relevant demos.
- [ ] Add or update test case.
- [ ] Add or update relevant TypeScript definitions.

### CODE REVIEW

File: packages/s2-core/src/ui/hd-adapter/index.ts [hunk 1]
```diff
@@ -104,24 +115,34 @@ export class HdAdapter {
       options: { width, height },
     } = this.spreadsheet;
     const canvas = this.spreadsheet.getCanvasElement();
+    const currentRatio = Math.ceil(ratio);
```
Comment (lijinke666) [inline packages/s2-core/src/ui/hd-adapter/index.ts:118]: 如果是窗口缩放场景, DPR 可能是 1.2 , 也可能是 1.2123123 这种, 没啥意义, 统一取整
