### PR TITLE
fix(interaction): add brush move distance validate

### LINKED ISSUE #315: 🐛单元格点击事件响应行为不准确
### 🖋 Description
1. 使用onColCellClick覆盖tooltip时 会经常出现原生tooltip，不是最后一列（？）的指标上容易出现
image

2. 单元格的刷选操作判定
正常点击还是比较容易触发刷选，出现合计tooltip，是否可以加个移动距离校验
image

### 🔗 Reproduce Link
https://riddle.alibaba-inc.com/riddles/3ee3b8e8

### PR DESCRIPTION
**Pull request by lijinke666**
### 👀 PR includes

🐛 Bugfix

- [x] Bug fix issue #0

🔧 Chore

- [x] Test case

### 📝 Description

增加刷选鼠标移动端距离校验, 避免单选时鼠标轻微移动判断为刷选的情况
加了 5px 的有效距离, 试了下还行

### 🖼️ Screenshot

|  Before  |  After  |
|----|----|
|  image |  image|

### 🔗 Related issue link

close #315

### CODE REVIEW

File: packages/s2-core/src/interaction/brush-selection.ts [hunk 1]
```diff
@@ -33,6 +33,8 @@ export class BrushSelection extends BaseEvent implements BaseEventImplement {
 
   public brushSelectionStage = InteractionBrushSelectionStage.UN_DRAGGED;
 
+  private brushValidMoveDistance = 5;
```
Comment (wjgogogo) [inline packages/s2-core/src/interaction/brush-selection.ts:36]:
```suggestion
  private brushMinimumMoveDistance = 5;
```

File: packages/s2-core/src/interaction/brush-selection.ts [hunk 2]
```diff
@@ -104,19 +106,31 @@ export class BrushSelection extends BaseEvent implements BaseEventImplement {
...
       this.setBrushSelectionStage(InteractionBrushSelectionStage.UN_DRAGGED);
     });
   }
 
+  private isValidBrushSelection() {
+    if (this.brushSelectionStage !== InteractionBrushSelectionStage.DRAGGED) {
+      return false;
+    }
+    const { start, end } = this.getBrushRange();
+    const isValidMoveRange =
```
Comment (wjgogogo) [inline packages/s2-core/src/interaction/brush-selection.ts:127]:
```suggestion
    const movedEnoughDistance =
```

**Review by wjgogogo — APPROVED** [review]
