### PR TITLE
fix(scroll): 修复点击滚动条滑道区域表格渲染空白 close #1764 #1780

### LINKED ISSUE #1764: 🐛表格内有滚动条时，点击滚动条空白区域，表格内变为空白
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       |      1.30.0     |

### Sheet Type

- [x] PivotSheet
- [x] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet

### 🖋 Description

表格内有滚动条时，点击滚动条空白区域，表格内变为空白，数据无法展示

### ⌨️ Code Snapshots

任意官网示例都可以复现该问题

### 🔗 Reproduce Link

https://s2.antv.vision/zh/examples/case/performance-compare#table

bug

### 🤔 Steps to Reproduce

表格内有滚动条时，点击滚动条空白区域，表格内变为空白，数据无法展示

### 😊 Expected Behavior

表格内有滚动条时，点击滚动条空白区域，表格滚动到对应位置

### 😅 Current Behavior

表格内变为空白，数据无法展示

### 💻 System information

Microsoft Edge
版本 105.0.1343.42 (正式版本) (arm64)
macOS  12.6

### LINKED ISSUE #1784: 🐛Uncaught TypeError: Cannot read properties of undefined (reading 'thumbOffset')
### 🏷 Version

| Package      | Version |
| -------------- | --------- |
| @antv/s2       |      1.30.0    |
| @antv/s2-react |          |
| @antv/s2-vue   |          |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet

### 🖋 Description

当左侧表头中**有**横向滚动条，但是右侧主内容区域**无**横向滚动条时。此时鼠标在主内容区域横向滚动(macOS)，会报如下错误：

```
Uncaught TypeError: Cannot read properties of undefined (reading 'thumbOffset')
    at t.isScrollToRight (styles-f9f9639cce878b4ffda0.js:1:5713306)
    at t.isHorizontalScrollOverTheViewport (styles-f9f9639cce878b4ffda0.js:1:5713912)
    at t.isScrollOverTheViewport (styles-f9f9639cce878b4ffda0.js:1:5714091)
    at HTMLCanvasElement.onWheel (styles-f9f9639cce878b4ffda0.js:1:5714995)
```

### ⌨️ Code Snapshots

官方示例即可复现：https://s2.antv.vision/zh/examples/basic/pivot#grid

### 🔗 Reproduce Link

官方示例即可复现：https://s2.antv.vision/zh/examples/basic/pivot#grid

### 🤔 Steps to Reproduce

访问官方示例：https://s2.antv.vision/zh/examples/basic/pivot#grid

1. 拖拽省份宽度，使得左侧表头**出现**横向滚动条
2. 如果右侧主内容区域出现横向滚动条，调小主内容字段宽度，使**不要出现**横向滚动条
3. 鼠标在主内容区域中横向滚动(macOS可双指横向滚动)，此时会报错。

image

### PR DESCRIPTION
**Pull request by lijinke666**
### 👀 PR includes

🐛 Bugfix

- [x] Solve the issue and closes #1784 #1780 #1764 

### 📝 Description

1. 修复 点击横/纵向滚动条的滑道时, 表格渲染空白 (透视表/明细表都有问题)
2. 修复 行头有滚动条, 数值区域无滚动条, 在数值区域滚动时报错

### 🖼️ Screenshot

| Before | After |
| ------ | ----- |
| Kapture 2022-09-27 at 11 20 52 | Kapture 2022-09-27 at 11 19 27 |

### 🔗 Related issue link

close #1784 #1780 #1764 

### 🔍 Self-Check before the merge

- [ ] Add or update relevant docs.
- [ ] Add or update relevant demos.
- [ ] Add or update test case.
- [ ] Add or update relevant TypeScript definitions.

### CODE REVIEW

File: packages/s2-core/src/ui/scrollbar/index.ts [hunk 1]
```diff
@@ -360,10 +367,10 @@ export class ScrollBar extends Group {
   };
 
   // 点击滑道的事件回调,移动滑块位置
-  private onTrackClick = (event: MouseEvent) => {
+  private onTrackClick = (event: GEvent) => {
     const offset = this.isHorizontal
-      ? event.offsetX - this.position.x - this.thumbLen / 2
-      : event.offsetY - this.position.y - this.thumbLen / 2;
+      ? event.x - this.position.x - this.thumbLen / 2
```
Comment (lijinke666) [inline packages/s2-core/src/ui/scrollbar/index.ts:372]: 滑道是 G 的 图层, 没有 offsetX 和 offsetY, 导致算出来的 offset 是 NaN

**Review by wjgogogo — APPROVED** [review]
