### PR TITLE
fix: 修复滚动边界问题 close #2720

### LINKED ISSUE #2720: 🐛滚动边界问题：表格和父容器的滚动条会同时滚动
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |    2.0.0-next.20    |
| @antv/s2-react |    2.0.0-next.19    |

### Sheet Type

- [x] PivotSheet
- [x] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

滚动表格的时候，表格和父容器的滚动条会同时滚动：

file

### ⌨️ Code Snapshots

无

### 🔗 Reproduce Link

无

### 🤔 Steps to Reproduce

本地 pnpm react:playground 后，查看 ”绘制 G2 图表“ tab，在图表中滚动鼠标可复现

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |    Mac: 12.6.3     |
| Browser |    Chrome: 124.0.6367.92    |

### PR DESCRIPTION
**Pull request by wyh888**
### 👀 PR includes

🐛 Bugfix

- [x] Solve the issue and close #2720 

#### 背景

滚动表格的时候，表格和父容器的滚动条会同时滚动：

file

#### 原因

image

`passive` 设置为 `true` 使浏览器忽略了 `preventDefault`，滚动事件会冒泡到父元素，导致父元素开始滚动。

### 🖼️ Screenshot

| Before | After |
| ------ | ----- |
| file  |   |

### 🔗 Related issue link

close #2720

### 🔍 Self-Check before the merge

- [ ] Add or update relevant docs.
- [ ] Add or update relevant demos.
- [ ] Add or update test case.
- [ ] Add or update relevant TypeScript definitions.

### CODE REVIEW

File: packages/s2-core/src/facet/base-facet.ts [hunk 1]
```diff
@@ -505,7 +505,7 @@ export abstract class BaseFacet {
   onContainerWheelForPc = () => {
     const canvas = this.spreadsheet.getCanvasElement();
 
-    canvas?.addEventListener('wheel', this.onWheel, { passive: true });
+    canvas?.addEventListener('wheel', this.onWheel);
```
Comment (lijinke666) [inline packages/s2-core/src/facet/base-facet.ts:508]: https://github.com/antvis/S2/pull/2631/files#diff-fba3ae1769f35556d3d9df253ed0ebef48d286d10a9381e58f1282a851cf2953R509

升级到 G 6.0 性能优化引入的, 是有别的考虑吗? @wjgogogo

**Review by wjgogogo — APPROVED** [review]

**Review by wjgogogo — APPROVED** [review]
