### PR TITLE
fix:  修复 vue playground 启动失败

### LINKED ISSUE #2103: 🐛next分支vue源码playground启动不了
| Package        | Version |
| -------------- | ------- |
| @antv/s2       |  2.0.0-next.5       |
| @antv/s2-react |  2.0.0-next.5       |
| @antv/s2-vue   |  2.0.0-next.5       |

### 🖋 Description

运行vue:playground会报错，提示找不到一些依赖

1677636709507_F22C50A8-DBF0-4629-9836-343C3F6F451B

### PR DESCRIPTION
**Pull request by wjgogogo**
### 👀 PR includes

✨ Feature

- [ ] New feature

🎨 Enhance

- [ ] Code style optimization
- [ ] Refactoring
- [ ] Change the UI
- [ ] Improve the performance
- [ ] Type optimization

🐛 Bugfix

- [x] Solve the issue and close #2103 

🔧 Chore

- [ ] Test case
- [ ] Docs / demos update
- [ ] CI / workflow
- [ ] Release version
- [ ] Other ()

### 🖼️ Screenshot

| Before | After |
| ------ | ----- |
| ❌      | ✅     |

### 🔍 Self-Check before the merge

- [ ] Add or update relevant docs.
- [ ] Add or update relevant demos.
- [ ] Add or update test case.
- [ ] Add or update relevant TypeScript definitions.

### CODE REVIEW

File: packages/s2-vue/playground/App.vue [hunk 1]
```diff
@@ -1,6 +1,13 @@
...
 /* eslint-disable no-console */
-import { CellTypes, DataType, S2DataConfig, S2Options } from '@antv/s2';
+import {
+  CellTypes,
+  type S2DataConfig,
+  type S2Options,
+  type Query,
+  type Data,
+  type RawData,
+} from '@antv/s2';
```
Comment (wjgogogo) [inline packages/s2-vue/playground/App.vue:10]: 现在配置更严格，需要区分 type 和 value

**Review by lcx-seima — APPROVED** [review]

File: packages/s2-vue/playground/App.vue (hunk 1 above)
Comment (xiaochong44) [reply packages/s2-vue/playground/App.vue:10]: 我本地按你这样改还是不行，提示找不到@antv/s2和@antv/s2-shared这两个包，我看设置也和react一样的
image
