### PR TITLE
fix: :bug: 修复列头小计总计位置漂移问题， close #836

### LINKED ISSUE #836: 🐛 合计列头显示出错
### 🏷 Version

1.1.1 版本合计列头显示出错，当列小记项大于两个时出现列头漂移问题

image

| Package      | Version |
| -------------- | --------- |
| @antv/s2       | 1.1.1        |
| @antv/s2-react | -         |

### PR DESCRIPTION
**Pull request by xingwanying**
### 👀 PR includes

🐛 Bugfix

- [x] Solve the issue and close #836 

### 🖼️ Screenshot

| Before | After |
| ------ | ----- |
| ❌ image | ✅  image|

### CODE REVIEW

File: packages/s2-core/__tests__/bugs/issue-368-spec.ts [hunk 1]
```diff
@@ -48,7 +48,7 @@ describe('Total Cells Rendering Test', () => {
     expect(rowSubTotalNodes[0].y).toEqual(30);
 
     expect(colSubTotalNodes[0].width).toEqual(192);
-    expect(colSubTotalNodes[0].height).toEqual(90);
+    expect(colSubTotalNodes[0].height).toEqual(60);
```
Comment (lijinke666) [inline packages/s2-core/__tests__/bugs/issue-368-spec.ts:51]: 改断言是预期吗? 意思是之前那个高度不对?

**Review by lijinke666 — APPROVED** [review]
