### PR TITLE
fix: 修复树状角头，当有存在icon时，内容与box宽度恰好相等，出现换行 close #2389

### LINKED ISSUE #2389: 🐛树状表，角头存在 action icon 时出现换行
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |  1.2.0  |
| @antv/s2-react |  1.3.3  |
| @antv/s2-vue   |   -     |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description
在线实例：https://codesandbox.io/s/blissful-microservice-5gxjjq?file=/index.ts
🐛树状表，角头存在 action icon 时出现换行
image

### 🔗 Reproduce Link
https://codesandbox.io/s/blissful-microservice-5gxjjq?file=/index.ts

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |         |
| Browser |         |

### PR DESCRIPTION
**Pull request by NoobNotN**
### 👀 PR includes

- [ ] Type optimization

🐛 Bugfix

- [x] Solve the issue and close #0

### 📝 Description
fix: 修复树状角头，当有存在icon时，内容与box宽度恰好相等，出现换行 close#2389

### 🖼️ Screenshot

| Before | After |
| ------ | ----- |
| image      | image    |

### 🔍 Self-Check before the merge

- [x] Add or update relevant docs.
- [x] Add or update relevant demos.
- [x] Add or update test case.
- [x] Add or update relevant TypeScript definitions.

### CODE REVIEW

File: packages/s2-core/__tests__/unit/facet/layout/col-node-width-spec.ts [hunk 1]
```diff
@@ -53,7 +53,7 @@ describe('Col width Test', () => {
       });
       s2.render();
       const { colLeafNodes } = s2.facet.layoutResult;
-      expect(Math.round(colLeafNodes[0].width)).toBe(339);
+      expect(Math.round(colLeafNodes[0].width)).toBe(338);
```
Comment (NoobNotN) [inline packages/s2-core/__tests__/unit/facet/layout/col-node-width-spec.ts:56]: 树状行头宽度增加1，列结点响应减少，下同

**Review by lijinke666 — APPROVED** [review]
