### PR TITLE
fix(table-sheet): 修复明细表配置自定义行高后展示异常 close #2501

### LINKED ISSUE #2501: 明细表设置列高度存在一些问题🐛
### 🏷 Version

| Package        | Version |
| -------------- | ------- |
| @antv/s2       |  1.53.0  |
| @antv/s2-react |  1.46.0  |
| @antv/s2-vue   |   -     |

### Sheet Type

TableSheet（明细表）

### 🖋 Description
打开就可以看到，当前行明细表表格数据是2行，但是设置了rowCfg.heightByField之后，就显示一行了

### ⌨️ Code Snapshots
https://riddle.alibaba-inc.com/riddles/ba294dfd
### 🔗 Reproduce Link
https://riddle.alibaba-inc.com/riddles/ba294dfd

### 🤔 Steps to Reproduce
打开就可以看到，当前行明细表表格数据是2行，但是设置了rowCfg.heightByField之后，就显示一行了
### 😊 Expected Behavior
将两行数据都展示出来

### 😅 Current Behavior
打开就可以看到，当前行明细表表格数据是2行，但是设置了rowCfg.heightByField之后，就显示一行了

### 💻 System information

| Environment | Info |
| ------- | ------- |
| System  |   mac      |
| Browser |    chrome： 120.0.6099.129     |

### PR DESCRIPTION
**Pull request by lijinke666**
### 👀 PR includes

🐛 Bugfix

- [x] Solve the issue and close #2501

### 📝 Description

在 https://github.com/antvis/S2/pull/2416 支持冻结首行后, 抽象了 `FrozenFacet` 类, 导致继承链路改变, 执行时序有问题, 在用户配置了 `rowCfg.heightByField` 后布局错误

```ts
const s2Options: S2Options = {
  style: {
    rowCfg: {
      heightByField: {
        '0': 100,
        '1': 150,
      },
    },
  },
};
```

```diff
public init() {
-  super.init();
-  this.initRowOffsets();

+  this.initRowOffsets();
+  super.init();
}
```

### 🖼️ Screenshot

| Before | After |
| ------ | ----- |
| image | image |

### 🔍 Self-Check before the merge

- [ ] Add or update relevant docs.
- [ ] Add or update relevant demos.
- [ ] Add or update test case.
- [ ] Add or update relevant TypeScript definitions.

### CODE REVIEW

File: packages/s2-core/src/facet/frozen-facet.ts [hunk 1]
```diff
@@ -689,27 +688,6 @@ export abstract class FrozenFacet extends BaseFacet {
     return { colCount, trailingColCount };
   };
 
-  private initRowOffsets() {
```
Comment (lijinke666) [inline packages/s2-core/src/facet/frozen-facet.ts:692]: 这一块是明细表特有的逻辑, 不需要写在基类中

**Review by wjgogogo — APPROVED** [review]
