### PR TITLE
fix(layout): 修复自定义列头采样错误导致行角头不显示 close #2117

### LINKED ISSUE #2117: 🐛next自定义列头行标题不显示
| Package        | Version |
| -------------- | ------- |
| @antv/s2       | 2.0.0-next.5        |
| @antv/s2-react | 2.0.0-next.5        |
| @antv/s2-vue   | 2.0.0-next.5        |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description

自定义列头时，如果第一列的层级数小于第二列，角头的行标题显示不出来，
如下图

image

### PR DESCRIPTION
**Pull request by lijinke666**
### 👀 PR includes

✨ Feature

- [ ] New feature

🎨 Enhance

- [ ] Code style optimization
- [ ] Refactoring
- [ ] Change the UI
- [ ] Improve the performance
- [ ] Type optimization

🐛 Bugfix

- [x] Solve the issue and close #2117

🔧 Chore

- [ ] Test case
- [ ] Docs / demos update
- [ ] CI / workflow
- [ ] Release version
- [ ] Other ()

### 📝 Description

布局采样的节点都是第一列的, 如果自定义列头第一列节点数量小于其他列时, 会导致单元格高度计算错误, 从而影响角头的显示

> 预期是 红色数字, 实际是绿色数字

image

### 🖼️ Screenshot

| Before | After |
| ------ | ----- |
| image | image |

### 🔍 Self-Check before the merge

- [ ] Add or update relevant docs.
- [ ] Add or update relevant demos.
- [ ] Add or update test case.
- [ ] Add or update relevant TypeScript definitions.

### CODE REVIEW

File: packages/s2-core/src/facet/pivot-facet.ts [hunk 1]
```diff
@@ -158,7 +158,7 @@ export class PivotFacet extends BaseFacet {
       layoutResult;
 
     let preLeafNode = Node.blankNode();
-    const allNodes = colsHierarchy.getNodes();
+    const colNodes = colsHierarchy.getNodes();
```
Comment (stone-lyl) [inline packages/s2-core/src/facet/pivot-facet.ts:161]: allColNodes

**Review by stone-lyl — APPROVED** [review]
