### PR TITLE
fix(layout): 修复行头收起全部时, 自定义列头被折叠的问题 closes #2018 #2019

### LINKED ISSUE #2018: next版本自定义列头平铺模式显示bug🐛
| Package        | Version |
| -------------- | ------- |
| @antv/s2       |  2.0.0-next.3  |
| @antv/s2-react | 2.0.0-next.3   |
| @antv/s2-vue   |  2.0.0-next.3   |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description
自定义列表默认平铺模式显示不正确行数据没有显示出来，如下面默认没有显示出类别和子类，需要切换到树状再切换回平铺才会正常

GIF 2022-12-23 16-35-07

### LINKED ISSUE #2019: next版本自定义列头树状模式bug🐛
| Package        | Version |
| -------------- | ------- |
| @antv/s2       |  2.0.0-next.3       |
| @antv/s2-react | 2.0.0-next.3        |
| @antv/s2-vue   | 2.0.0-next.3        |

### Sheet Type

- [x] PivotSheet
- [ ] TableSheet
- [ ] GridAnalysisSheet
- [ ] StrategySheet
- [ ] EditableSheet

### 🖋 Description
自动义列头时，如果把列的角头名称设为空字符，达到隐藏的效果时，行收缩时也同步把列收缩掉了
GIF 2022-12-23 16-45-29

### PR DESCRIPTION
**Pull request by lijinke666**
### 👀 PR includes

🐛 Bugfix

- [x] Solve the issue and closes #2018 #2019 

### 📝 Description

1. 修复行头收起全部时, 自定义列头错误被折叠, 导致不展示的问题.
2. 修复自定义列头时, 行头维度不展示的问题.

### 🖼️ Screenshot

| Before | After |
| ------ | ----- |
| Kapture 2024-03-28 at 16 47 29 | Kapture 2024-03-28 at 16 45 24 |
| image | image |

### 🔍 Self-Check before the merge

- [ ] Add or update relevant docs.
- [ ] Add or update relevant demos.
- [ ] Add or update test case.
- [ ] Add or update relevant TypeScript definitions.

### CODE REVIEW

File: packages/s2-core/src/facet/layout/build-row-custom-tree-hierarchy.ts [hunk 1]
```diff
@@ -44,7 +51,9 @@ export const buildCustomTreeHierarchy = (params: CustomTreeHeaderParams) => {
     const isCollapsed = isDefaultCollapsed ?? (collapseAll || defaultCollapsed);
 
     // TODO: 平铺模式支持 折叠/展开
-    const isCollapsedNode = spreadsheet.isHierarchyTreeType() && isCollapsed;
+    // https://github.com/antvis/S2/issues/2019
+    const isCollapsedNode =
+      spreadsheet.isHierarchyTreeType() && isRowHeader && isCollapsed;
```
Comment (lijinke666) [inline packages/s2-core/src/facet/layout/build-row-custom-tree-hierarchy.ts:56]: 行头全部收起时, 如果是自定义列头, 本质上也是树状结构, 所以走的是 `buildCustomTreeHierarchy` 链路, 此时列头也会被折叠

File: packages/s2-core/src/data-set/custom-grid-pivot-data-set.ts [hunk 2]
```diff
@@ -5,9 +5,10 @@ import { CustomTreePivotDataSet } from './custom-tree-pivot-data-set';
 export class CustomGridPivotDataSet extends CustomTreePivotDataSet {
   processDataCfg(dataCfg: S2DataConfig): S2DataConfig {
     const valueInCols = !this.spreadsheet.isCustomRowFields();
+    const originalRows = dataCfg.fields.rows || [];
     const rows = valueInCols
-      ? [EXTRA_FIELD]
```
Comment (lijinke666) [inline packages/s2-core/src/data-set/custom-grid-pivot-data-set.ts:9]: image

**Review by wjgogogo — APPROVED** [review]
